services:

  Apps.mooc.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.mooc.controllers.VideoPutController:
    class: ../../controllers/VideoPutController
    arguments: ["@Mooc.Videos.application.VideoCreator", "@Shared.domain.Logger"]